apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ft588f0dc-go 
  janus-idp.io/tekton: ft588f0dc-go
  backstage.io/kubernetes-id: ft588f0dc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ft588f0dc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml