apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ft588f0dc-go
  janus-idp.io/tekton: ft588f0dc-go
  backstage.io/kubernetes-id: ft588f0dc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ft588f0dc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
